# Generated by Django 5.2.5 on 2026-01-05 17:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeecalculator',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0200'), max_digits=5),
        ),
    ]
